---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skyrim-together
  namespace: skyrim-together
spec:
  selector:
    matchLabels:
      app: skyrim-together
  serviceName: "skyrim-together"
  replicas: 0
  template:
    metadata:
      labels:
        app: skyrim-together
    spec:
      containers:
        - name: skyrim-together
          image: tiltedphoques/st-reborn-server:latest
          ports:
            - name: "game"
              containerPort: 10578
              protocol: UDP
          volumeMounts:
            - name: skyrim-together-config
              mountPath: /home/server/config
            - name: skyrim-together-data
              mountPath: /home/server/Data
            - name: skyrim-together-logs
              mountPath: /home/server/logs
  volumeClaimTemplates:
    - metadata:
        name: skyrim-together-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: skyrim-together-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: skyrim-together-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
