---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wol-deployment
  namespace: wol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wol-host
  template:
    metadata:
      labels:
        app: wol-host
    spec:
      containers:
        - name: wol-container
          image: ghcr.io/seriousm4x/upsnap:4.3.4
          ports:
            - name: "wol-http"
              containerPort: 8090
              protocol: TCP
