apiVersion: v1
kind: Namespace
metadata:
  name: wol-host
---
apiVersion: v1
kind: Service
metadata:
  name: wol-host
  labels:
    app: wol-host
  namespace: wol-host
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: "http"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: wol-host
