apiVersion: v1
kind: Namespace
metadata:
  name: wol
---
apiVersion: v1
kind: Service
metadata:
  name: wol-host
  labels:
    app: wol-host
  namespace: wol
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: "wol-http"
      port: 8080
      protocol: TCP
      targetPort: 8090
  selector:
    app: wol-host
