apiVersion: v1
kind: Namespace
metadata:
  name: satisfactory
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
  namespace: satisfactory
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: "game"
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: "api"
      port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: satisfactory
