---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:sha256:fb813404691ee74a3e3934ae80362eb83360da7361d16ae5371c64da18bb42cb
          env:
            - name: DEBUG
              value: "false"
            - name: MAXPLAYERS
              value: "8"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SKIPUPDATE
              value: "false"
            - name: STEAMBETA
              value: "false"
          ports:
            - name: "api"
              containerPort: 7777
              protocol: TCP
            - name: "game"
              containerPort: 7777
              protocol: UDP
          volumeMounts:
            - name: satisfactory-config
              mountPath: /config
            - name: satisfactory-data
              mountPath: /config/gamefiles
  volumeClaimTemplates:
    - metadata:
        name: satisfactory-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: satisfactory-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
