---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBm+a/Q3NGCSeMjcAP/+4G9CnHxE397Xz89+wyJqBYhYtdSRk2Zpj4GM7U4GDusq/zO0Vu6ndkFExf9mmLhgiziPmVTNbqOzjj9VaSwAOID6y7w0sH8aiJXha/If5mk0qB/qScfcx1FshDICgzceVnLADoFWpSsRdSkpx3u0gEcQKQM63F7YIKEKYmqVx+SJ9D0DBV6LFC++MLYp0Ghk03UGvrYWXZ+D8PGL1rEhPRynFj4sIGD27k+vgrEa6HslLFfkhdQvrxDWcWT61AXzDSk2Ha+emK2YA4LspYC0fUmf+nSD1zfvfxTNCK4kmIya8/V8AX8YAejh9C0k23sv1KkMf9yTsKGuGZhN+NOXR0jK+y/hzfk3fpzUnJadhKlyD67FH+pSMq6/Hx02e9vH40mzX5DRdqh+ewH9+MJDH7TLQeHTYbN/LZApHqg8QEjGts32pnKMwWQc9BmfWJ1yvkj6v9mafUSv8X2Dw67ra6bfdP6gRE43KaryvJXT6szxe8kKDNCz2APF+If3HCp8ZAUVYy3q2UbIl5XyhlPET/nTRSGLTOz2Cn20PdAE/tZkB8oNYQd8EdjVnCk1armjJKBqWvNCWUYHMVurT42FuNSIrTsBwp1iB8SP0KgKOh2F93NaWcXLNktECFCrXU/r92mc70Q+ZP4KCxFB4ywr6+FzAGXL0IKGjSA89BX6CJs9A9B1ulUC/WYKs5ewGOvG1Mvdw==
    client_secret: AgA1F2ogVWXn9bn/BLMlUWsv3hy8sV3uYifsko9OJChFQlLHG6W4y+0DUoeTSOhnTmHWlEkYoPsfT087yHuN1eQr2Q3U7dbWHLGndW/ur6vxUnRVE+Wixvb5JnXDwRq4vKP9Q3xtdmzdskjiJvEz06YIpn9XrOm+zoap872cKc/t3h23kMN5LOij/PqiTuOIeFMp+Pg5XngVXtLpyNLbRhOQV+wG2uDGHTGHkxnSYsTiJS3EVaOcPc2Jtyg0dON84q9kjx3Aw1EAUKbc1n2vMq/Sv1fCzB2PO9sxfjwWujwUU9II9vKIpgJ+scIhO8uZMYsZhnD5IpTrq3RKBCl+di2RINF54GqZBFgKKvbjXDTB/rHJRc8ydv7yoq1b5qebrxlibllit+1sAMZh48DRntJOp+0oNEY++yxYWFM0Y2MhLqMSz5vyjUPh369kYEPs1BbKiYAVIHFcJS/7DgTkUrazrjza9z2hbdROFkjPIKiTntsLqe6SIs/wzxk8HmDunCvkui6URDsJxkCzWnWDyUBcGMcwehBngrSl7+VmwIv0OmR1cucx7T8C+Bt48xXTRZPAwa4sMGytIEoSjwoeP1PlF3MJ1eoqZlhf+6rQaEpIumNBJHUAWa72x6zXlpoNArxaB/0u7Tb2egd+WPSHmMSyBh2huis3go8txfjRBDowp0JrmwYrpJHneZRPn9Te4I6lLaN1EMihLj2dSicFlGJCq/DhMp4jnsZbnlQmtaWtVgOjiKoPFeJz03hmO+mKXYlkd8kWq8Z7zJ8c8+neXRRR
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
